// define a variable to import the <Verifier> or <renamedVerifier> solidity contract generated by Zokrates
var Verifier = artifacts.require('./verifier');
var Proof = require('../../zokrates/code/square/proof.json');

contract('VERIFIER', accounts => {

    describe('zK-SNARKS VALIDATION PROOF', function () {
        beforeEach(async () => {
            this.contract = await Verifier.new();
        });

        it('VALIDATE CORRECT PROOF', async () => {
            let verified = await this.contract.verifyTx(Proof.proof, Proof.inputs)
            assert.equal(verified, true);
        })

        it('VALIDATE PROOF IS NOT CORRECT', async () => {
            let verified = await this.contract.verifyTx(Proof.proof, [1, 3]);
            assert.equal(verified, false);
        })
    
    })

})